{{- if .Values.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "prism-agent-base-path-cert"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{ template "labels.common" . }}
spec:
  secretName: "prism-agent-base-path-secret"
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  {{- range .Values.ingress.applicationUrls }}
    - {{ . }}
  {{- end }}
{{- end }}