apiVersion: v1
entries:
  prism-agent:
    - apiVersion: v2
      appVersion: 1.31.0
      created: "2024-03-20T18:57:40.265443237Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 2b70776d21bbaa35d252b5a84f821f27e28918592ac689fea01888087d889df3
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.31.0.tgz
      version: 1.31.0
    - apiVersion: v2
      appVersion: 1.30.1
      created: "2024-03-20T18:57:40.254521753Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 8ef2ce679bd5f0605309f08f5cefa46a1a7c4eebe066d160dbdfe6a9a39e9dc2
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.30.1.tgz
      version: 1.30.1
    - apiVersion: v2
      appVersion: 1.30.0
      created: "2024-03-20T18:57:40.243928266Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 7ec6e27fb040e4184a025ec99a4ba0f22484b02309223814e1f7646ecaf477d6
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.30.0.tgz
      version: 1.30.0
    - apiVersion: v2
      appVersion: 1.29.0
      created: "2024-03-20T18:57:40.2339365Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 928643b46409456566e343746d0eae0c258cf88260e4975769ae4e0372126768
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.29.0.tgz
      version: 1.29.0
    - apiVersion: v2
      appVersion: 1.28.0
      created: "2024-03-20T18:57:40.223094151Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: b2ebdf904787158c5e7322376397f6023313600f676c29df30765dad8175d50b
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.28.0.tgz
      version: 1.28.0
    - apiVersion: v2
      appVersion: 1.27.0
      created: "2024-03-20T18:57:40.212806243Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 6476368c0c1537c5c84b4d2072d50ac522a1d6db791eb67fcd1fdeba86138d84
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.27.0.tgz
      version: 1.27.0
    - apiVersion: v2
      appVersion: 1.26.0
      created: "2024-03-20T18:57:40.202753019Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: f3405b5bd8c3522a62a5130b5e6733c519a7c88f1ad37c85ee608a4115e087f9
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.26.0.tgz
      version: 1.26.0
    - apiVersion: v2
      appVersion: 1.25.0
      created: "2024-03-20T18:57:40.19166764Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 4bfbd942f4d6371157f9762fa52a3ec62e1d064c200fe770f287b0f34f36e676
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.25.0.tgz
      version: 1.25.0
    - apiVersion: v2
      appVersion: 1.24.0
      created: "2024-03-20T18:57:40.181190039Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 368e8b81d34e54e244779ed218b6a6885b56f1616f761b2b217a13e21fb5078a
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.24.0.tgz
      version: 1.24.0
    - apiVersion: v2
      appVersion: 1.23.0
      created: "2024-03-20T18:57:40.169775233Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: cd1a3beba47786eb5ee388a6761484b628a797802d504e815c119526afaa91f7
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.23.0.tgz
      version: 1.23.0
    - apiVersion: v2
      appVersion: 1.22.0
      created: "2024-03-20T18:57:40.15980116Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: be3d146eba5e099d7f2e7cf9338a4a6cb238f19cb3f458864fe88778505bd403
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.22.0.tgz
      version: 1.22.0
    - apiVersion: v2
      appVersion: 1.21.1
      created: "2024-03-20T18:57:40.148808367Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: d97c1d2dc3f9dadb8642271b89ff2c2fb52f01e00c8aa5ca712ee1ccb77622d0
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.21.1.tgz
      version: 1.21.1
    - apiVersion: v2
      appVersion: 1.21.0
      created: "2024-03-20T18:57:40.138859211Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 12de363c93d6155ae492710ca6a365b5a4b429d40b0691f289528b7ac08119b2
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.21.0.tgz
      version: 1.21.0
    - apiVersion: v2
      appVersion: 1.20.1
      created: "2024-03-20T18:57:40.12694057Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 7890f9939ae1a0a143915d36ec3c401384195ccbeabee03fb921837b75aefb76
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.20.1.tgz
      version: 1.20.1
    - apiVersion: v2
      appVersion: 1.20.0
      created: "2024-03-20T18:57:40.116915211Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 004a72bf116850fa79017d94880684a9aac798a11825ce5b88ac4b34ed0dc862
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.20.0.tgz
      version: 1.20.0
    - apiVersion: v2
      appVersion: 1.19.1
      created: "2024-03-20T18:57:40.105906962Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: 077292fe1e1388a9d5db10b0e28869c2754928defa25f5a59dd12431bd058ba7
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.19.1.tgz
      version: 1.19.1
    - apiVersion: v2
      appVersion: 1.19.0
      created: "2024-03-20T18:57:40.095762398Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
        - condition: keycloak.enabled
          name: keycloak
          repository: https://charts.bitnami.com/bitnami
          version: 17.2.0
      description: A Helm chart for deploying prism-agent
      digest: faa036cfc70e35ca0ada898e4c0281f70a06d8855f55e37f24f9b529895b4a64
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.19.0.tgz
      version: 1.19.0
    - apiVersion: v2
      appVersion: 1.18.0
      created: "2024-03-20T18:57:40.085726944Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 5a803d916bc19c824aec9d39efb0206ff9a2a3b1932b276acaaf97c580f62387
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.18.0.tgz
      version: 1.18.0
    - apiVersion: v2
      appVersion: 1.17.0
      created: "2024-03-20T18:57:40.082551551Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: a53050003aedfd0a7d78014dfe9e819c6e2a1db442eeaac6971cff354cf0d3d4
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.17.0.tgz
      version: 1.17.0
    - apiVersion: v2
      appVersion: 1.16.4
      created: "2024-03-20T18:57:40.079722433Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 05c9159bea902724bb8c8c395bb00d5a3305602e8ace94fe0dd94c1064384fc5
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.16.4.tgz
      version: 1.16.4
    - apiVersion: v2
      appVersion: 1.16.3
      created: "2024-03-20T18:57:40.075981995Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 309200472891b513a19fad3c3a84745ee95afad6b4680924e81b497f4d8736d3
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.16.3.tgz
      version: 1.16.3
    - apiVersion: v2
      appVersion: 1.16.2
      created: "2024-03-20T18:57:40.073089218Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 0ffa1f3b0748da032ff40900bc4bb55e4a64c400b31cc8796880da4aa7557529
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger/identus-cloud-agent/main/infrastructure/charts/prism-agent-1.16.2.tgz
      version: 1.16.2
generated: "2024-03-20T18:57:40.069857861Z"
