name: Castor testing workflow

# Cancel previously running workflows if new commit pushed to the branch
# this will help to push fixes earlier and stop previous workflows
concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}-castor
  cancel-in-progress: true

# Default shell is `sh`
# which is old, use bourne-again version instead
defaults:
  run:
    shell: bash
    working-directory: castor/lib

on:
  # Run with every push to `main` branch
  # Run with each PR opened vs Castor
  push:
    branches:
      - main
    paths:
      - ".github/workflows/castor.yml"
      - "castor/**"
  pull_request:
    paths:
      - ".github/workflows/castor.yml"
      - "castor/**"

# Global environment variables for all jobs
env:
  ATALA_GITHUB_TOKEN: ${{ secrets.ATALA_GITHUB_TOKEN }}

jobs:
  build-and-test-castor:
    name: "Build and test Castor"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.11

      - name: Cache sbt
        uses: coursier/cache-action@v6.3
      
      - name: Run Scala formatter
        run: sbt scalafmtCheckAll
      
      - name: Build and test Castor
        run: sbt test

      - name: Aggregate test reports
        if: always()
        uses: ./.github/actions/aggregate-test-reports
        with:
          tests-dir: "castor/lib"

      - name: Publish test results
        # Publish even if the previous test step fails
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: "castor/lib/target/test-reports/**/TEST-*.xml"
          comment_title: "Castor Test Results"
          check_name: "Castor Test Results"
