name: Pollux testing workflow

## Cancel previously running workflows if new commit pushed to the branch
## this will help to push fixes earlier and stop previous workflows
concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}-pollux
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/pollux.yml"
      - ".github/workflows/scala-unit-tests.yml"
      - "pollux/**"
  pull_request:
    paths:
      - ".github/workflows/pollux.yml"
      - ".github/workflows/scala-unit-tests.yml"
      - "pollux/**"

jobs:
  build-and-test-pollux:
    uses: ./.github/workflows/scala-unit-tests.yml
    with:
      component-name: "Pollux Lib"
      component-dir: "pollux/lib"
    secrets: inherit
